[package]
name = "aoc-rs"
version = "0.1.0-alpha"
description = "Solutions to Advent of Code in Rust"
edition = "2024"
readme = "docs/README.md"
repository = "https://github.com/rrvsh/adventofcode"
license = "MIT"
keywords = ["cli"]
categories = ["command-line-utilities"]

[dependencies]

[lints.clippy]
correctness = "deny"
suspicious = "deny"
complexity = "deny"
perf = "deny"
style = "deny"
pedantic = "deny"
cargo = "deny"
nursery = "deny"
unwrap_used = "deny"
